travis:
  secure:
    BINSTAR_TOKEN: lBIH1xYLHxx3AvuOSu9cMbSbF36Oe5E9mTGZ2dtIvZcc9X/Ei1id5Usy914ugCkPlY8+Fk2rxVgPYvKqTl9IB50jiB2YTdBTvV8HkSlPaEzu0Y0oCXEz/cevjEec40RkwXyQhpplwBmlnzlMM5SBMBXEtgQ2TtRbCKMSl/F7mYYh45VVbi0HQLkB7vRA/5PzlCxq+mKoorf3u9YNpgmplAS/KQiLkX0a2aiknY/or6sUxAWisbXKUo/5sSmlTjc04Js2cuN4tYFlXyk4bmG0DySr1qINijResPW2r46XcK2oQv6tCqfNTaG47N89iB9MZPzoghSPe4bNqtovLmW/WxFepwONT4lyX8tRg0FiPNbtzehdilWdGpapcyyePvGFJtCmRJOJw55o5rWHyX07u9viROKFH6ekUN5BEmGvhuThn4Db5u7nmPcya1IY5kU1vKOf+c4u/A2o1zq5wRiGXOCZLFiA/5mUg56NgUsGxin80Mk3lpEm54H7D4MrGyPKUlwFHXJtfJHqVk+LxJ7+UH+NhNBFOeOQLaAKIydgGOv9gcJH8sez0sx4aPPiIXlvuxQSHuHeAEnATaV8wx1mSlBffzEbyu+mI10xdLFdyZg7AhYd1Y04p37F6xqgbiZhAj3OLIzLSa6E9Lr/dWAgK5WwNPEoCp9eHfEtp2dfyJY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
