travis:
  secure:
    BINSTAR_TOKEN: kRGTJMsZwWHBwNjmtpIknd3KlRQ8BOPDadvkL1PuJ1tXIs4MmYF1kbs5niEuMJsk0z2RgAp/glvOWww8BWlDnSugvM2XzNdXh3XNEg6QTOcEYFnGluqnt0LC2Wa1wzPlHfwC5TIWj+eVXR1/i68h0O2GWmfQXuXYwxc1Kiz5u+Mpk7cpKxIluQtxKJb9SpNgWyXtgMhA1LviEvU1GdrSQX5Or8NRLEY1yWxxnMQlJq+aV+Q23nhs53OtXnYMA+SGpqa3nDL9+6p1TVcZlDpvHEVSDPBOSSqqy957R3TF8GGD19xwdOgjIFeEkXzHPUdk6o9bzqfcUUBkL4Hsg61qNkfB4/ck+qODkINrgF5LFK6OVlC69ba0dcZ/Ufda3cKsPf+ld0F7RANE/UJ5SUUVQkaKQFymBZwRtZht/qXBc3acva1Vqro+INqEzLl5DvfGGF+Zqn6PrNG9NxGcp7XFE7buBMtMBJG4uEK4SfBQxrmUsr8kxOlv9ddEftd54v7sMb7I9PbyXooFskK88vMltiNmyL3aTpcIUO0YNP9VLwx9JDV0RrzewAGlVmH6qLCWsG/HeGjhqXsGVdypb9wgCITu4xjHqu0B3acGdlCFxnLHB/Cw8vXnA88UeZZOD6g7kCSdqbf5caoDTAtb65IV8wNuxFI1UWWccG+NA2nhzAE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
