travis:
  secure:
    BINSTAR_TOKEN: BP07lCU5j4Yn62DHV3wqim1z8DdPzG4u5OuZdufhQFIBPOGknQUYAgQI6UkMyJf0B3QCyVkNuINgEbfObUBAIsWVYztlWCncJ8efpvPXp/c7uuvLaGPQzpQxYZ4zMleuEFZTHOWejuFinEhTSwpA8KGRkAoTCt1DRnBpcjk6cmRFxUyyIvR7H+arl6Zel1Bwv1iYDyolcNTbyEq/HKwnyF9kA3QugFbl+uHPY4Y2k4xeXeeo0bA7jWDlaquC/Pc8kUfT12IGCK3bglKKVMIvTejqmOsUNwi6WIzKmZK8zl+Dxz1uxqsarC4mCtva93q8JIWWdJUXYvpt2opBh6PNjisCClOhPIkh7M0K9ZthySUPlSK+X5v52k1lHdDbz4Rstlxr0Dhno4erGY6FQSRoCn01VtkOT2MSQy71IeVHEPGdzKw+xUkg/Z09Nh51mD9nRILj/FRCw+K2W1k5vTOSQ52Zh5Z6CTRTslOByFYobfxQpf3HiYGpDo8zAvAPzeXVNB7TmlXTxW0u04Iiz6KOF98LS7SH8v/TYtLrHZV909xBGNU2sLuuRrRe/SV38SsSDeTVNXGkK65fSgCo9OKdfdBuBnHvPKF/CQOtmgFeTDkgd8/s0MkM0e6HXnfkFXZspJg+1wA+6Bm3yo3515916mYdVvkAVoVO6ldaoE3tk6s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
